[package]
name = "game-2048"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "game2048lib"
path = "src/main.rs"

[dependencies]
priority-queue = "1.3.2"
rand = "0.8.5"

