[package]
name = "game_2048"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "game_2048"
path = "src/main.rs"


[dependencies]
priority-queue = "1.3.2"
rand = "0.8.5"
rustc-hash = "1.1.0"

